Update commit-msg

diff --git a/git/hook-client/commit-msg b/git/hook-client/commit-msg
--- a/git/hook-client/commit-msg
+++ b/git/hook-client/commit-msg
@@ -1,19 +1,35 @@
-#!/bin/sh
-
-##
-# Description :
-#   This script is executed before a command "git commit".
-# Paremeter :
-#   $1: a file that is a buffer for the current commit message
-#       here normally .git/COMMIT_EDITMSG into the root of the Git project.
+#!/usr/bin/env sh
 #
+# .git/hooks/commit-msg
+#
+# Description:
+#   This script is executed before a command "git commit".
+#   Insert into commit message the current branch name between
+#   square brackets. It is useful for your git history, after merges
+#   and branch deletions ...
+#   For example, your current branch is master and your commit
+#   message is "First commit", automatically your commit message
+#   becomes "[master] First commit".
+# Paremeter:
+#   $1: file path name that is a buffer for the current commit message,
+#       that is to say .git/COMMIT_EDITMSG at the root of the git project.
+# Exit Status:
+#   0: The commit message is completed with the current branch name.
+#   1: Do nothing, an error occurred with a message on STDERR, because
+#      the commit message is empty.
 CURRENT_BRANCH_NAME="$(basename "$(git symbolic-ref HEAD)")"
 MESSAGE="$(cat "$1" | sed '/^#.*/d')"
 
-if [ -n "$MESSAGE" ]; then
-    echo "[$CURRENT_BRANCH_NAME] $MESSAGE" > "$1"
+if [ -n "${MESSAGE}" ]; then
+    if cat "$1" | head -1 | grep -q "^\[${CURRENT_BRANCH_NAME}\]"; then
+        # if the current branch name is already present at the beginning of
+        # message, don't put that again
+        echo "${MESSAGE}" > "$1"
+    else
+        echo "[${CURRENT_BRANCH_NAME}] ${MESSAGE}" > "$1"
+    fi
     exit 0
 else
-    echo "Aborting commit due to empty commit message."
+    echo >&2 "Aborting commit due to empty commit message."
     exit 1
 fi
